services:

  postgres:
    image: postgres:16
    container_name: postgres_dw
    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5


  airflow:
    build: .
    container_name: airflow
    restart: always

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8081:8080"

    environment:
      AIRFLOW_UID: 50000
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_URL}
      PYTHONPATH: /opt/airflow

    volumes:
      - ./main.py:/opt/airflow/main.py
      - ./etl:/opt/airflow/etl
      - ./utils:/opt/airflow/utils
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./.env:/opt/airflow/.env

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@gmail.com || true &&
      airflow standalone
      "

volumes:
  postgres_data:
